/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface CAPITTokenInterface extends utils.Interface {
  functions: {
    "BPS_DENOM()": FunctionFragment;
    "DEV_BPS()": FunctionFragment;
    "MINT_UNIT()": FunctionFragment;
    "PUBLIC_BPS()": FunctionFragment;
    "RESERVE_BPS()": FunctionFragment;
    "allowance(address,address)": FunctionFragment;
    "approve(address,uint256)": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "decimals()": FunctionFragment;
    "devVesting()": FunctionFragment;
    "genesisCutoffTimestamp()": FunctionFragment;
    "genesisInitialized()": FunctionFragment;
    "genesisSnapshotHash()": FunctionFragment;
    "initializeGenesis(uint256,uint64,bytes32,address,address,address)": FunctionFragment;
    "mintAuthority()": FunctionFragment;
    "mintWell(bytes32)": FunctionFragment;
    "name()": FunctionFragment;
    "owner()": FunctionFragment;
    "publicRecipient()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "reserveController()": FunctionFragment;
    "setMintAuthority(address)": FunctionFragment;
    "symbol()": FunctionFragment;
    "totalSupply()": FunctionFragment;
    "transfer(address,uint256)": FunctionFragment;
    "transferFrom(address,address,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "BPS_DENOM"
      | "DEV_BPS"
      | "MINT_UNIT"
      | "PUBLIC_BPS"
      | "RESERVE_BPS"
      | "allowance"
      | "approve"
      | "balanceOf"
      | "decimals"
      | "devVesting"
      | "genesisCutoffTimestamp"
      | "genesisInitialized"
      | "genesisSnapshotHash"
      | "initializeGenesis"
      | "mintAuthority"
      | "mintWell"
      | "name"
      | "owner"
      | "publicRecipient"
      | "renounceOwnership"
      | "reserveController"
      | "setMintAuthority"
      | "symbol"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "BPS_DENOM", values?: undefined): string;
  encodeFunctionData(functionFragment: "DEV_BPS", values?: undefined): string;
  encodeFunctionData(functionFragment: "MINT_UNIT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PUBLIC_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RESERVE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "devVesting",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "genesisCutoffTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "genesisInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "genesisSnapshotHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeGenesis",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "mintAuthority",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintWell",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "publicRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reserveController",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMintAuthority",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "BPS_DENOM", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "DEV_BPS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MINT_UNIT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PUBLIC_BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "RESERVE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "devVesting", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "genesisCutoffTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "genesisInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "genesisSnapshotHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeGenesis",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintWell", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publicRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMintAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "Approval(address,address,uint256)": EventFragment;
    "GenesisInitialized(uint256,uint64,bytes32,address,address,address)": EventFragment;
    "GenesisMetadata(uint64,bytes32)": EventFragment;
    "MintAuthoritySet(address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
    "WellMinted(bytes32,address,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GenesisInitialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GenesisMetadata"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MintAuthoritySet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WellMinted"): EventFragment;
}

export interface ApprovalEventObject {
  owner: string;
  spender: string;
  value: BigNumber;
}
export type ApprovalEvent = TypedEvent<
  [string, string, BigNumber],
  ApprovalEventObject
>;

export type ApprovalEventFilter = TypedEventFilter<ApprovalEvent>;

export interface GenesisInitializedEventObject {
  genesisSupply: BigNumber;
  cutoffTimestamp: BigNumber;
  snapshotHash: string;
  publicRecipient: string;
  reserveController: string;
  devVesting: string;
}
export type GenesisInitializedEvent = TypedEvent<
  [BigNumber, BigNumber, string, string, string, string],
  GenesisInitializedEventObject
>;

export type GenesisInitializedEventFilter =
  TypedEventFilter<GenesisInitializedEvent>;

export interface GenesisMetadataEventObject {
  cutoffTimestamp: BigNumber;
  snapshotHash: string;
}
export type GenesisMetadataEvent = TypedEvent<
  [BigNumber, string],
  GenesisMetadataEventObject
>;

export type GenesisMetadataEventFilter = TypedEventFilter<GenesisMetadataEvent>;

export interface MintAuthoritySetEventObject {
  mintAuthority: string;
}
export type MintAuthoritySetEvent = TypedEvent<
  [string],
  MintAuthoritySetEventObject
>;

export type MintAuthoritySetEventFilter =
  TypedEventFilter<MintAuthoritySetEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface TransferEventObject {
  from: string;
  to: string;
  value: BigNumber;
}
export type TransferEvent = TypedEvent<
  [string, string, BigNumber],
  TransferEventObject
>;

export type TransferEventFilter = TypedEventFilter<TransferEvent>;

export interface WellMintedEventObject {
  wellIdHash: string;
  to: string;
  amount: BigNumber;
  newTotalSupply: BigNumber;
  timestamp: BigNumber;
}
export type WellMintedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber],
  WellMintedEventObject
>;

export type WellMintedEventFilter = TypedEventFilter<WellMintedEvent>;

export interface CAPITToken extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CAPITTokenInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    BPS_DENOM(overrides?: CallOverrides): Promise<[number]>;

    DEV_BPS(overrides?: CallOverrides): Promise<[number]>;

    MINT_UNIT(overrides?: CallOverrides): Promise<[BigNumber]>;

    PUBLIC_BPS(overrides?: CallOverrides): Promise<[number]>;

    RESERVE_BPS(overrides?: CallOverrides): Promise<[number]>;

    allowance(
      owner: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    approve(
      spender: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    balanceOf(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    decimals(overrides?: CallOverrides): Promise<[number]>;

    devVesting(overrides?: CallOverrides): Promise<[string]>;

    genesisCutoffTimestamp(overrides?: CallOverrides): Promise<[BigNumber]>;

    genesisInitialized(overrides?: CallOverrides): Promise<[boolean]>;

    genesisSnapshotHash(overrides?: CallOverrides): Promise<[string]>;

    initializeGenesis(
      genesisSupply: PromiseOrValue<BigNumberish>,
      cutoffTimestamp: PromiseOrValue<BigNumberish>,
      snapshotHash: PromiseOrValue<BytesLike>,
      _publicRecipient: PromiseOrValue<string>,
      _reserveController: PromiseOrValue<string>,
      _devVesting: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    mintAuthority(overrides?: CallOverrides): Promise<[string]>;

    mintWell(
      wellIdHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    name(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    publicRecipient(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    reserveController(overrides?: CallOverrides): Promise<[string]>;

    setMintAuthority(
      _mintAuthority: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    symbol(overrides?: CallOverrides): Promise<[string]>;

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    transfer(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  BPS_DENOM(overrides?: CallOverrides): Promise<number>;

  DEV_BPS(overrides?: CallOverrides): Promise<number>;

  MINT_UNIT(overrides?: CallOverrides): Promise<BigNumber>;

  PUBLIC_BPS(overrides?: CallOverrides): Promise<number>;

  RESERVE_BPS(overrides?: CallOverrides): Promise<number>;

  allowance(
    owner: PromiseOrValue<string>,
    spender: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  approve(
    spender: PromiseOrValue<string>,
    value: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  balanceOf(
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  decimals(overrides?: CallOverrides): Promise<number>;

  devVesting(overrides?: CallOverrides): Promise<string>;

  genesisCutoffTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

  genesisInitialized(overrides?: CallOverrides): Promise<boolean>;

  genesisSnapshotHash(overrides?: CallOverrides): Promise<string>;

  initializeGenesis(
    genesisSupply: PromiseOrValue<BigNumberish>,
    cutoffTimestamp: PromiseOrValue<BigNumberish>,
    snapshotHash: PromiseOrValue<BytesLike>,
    _publicRecipient: PromiseOrValue<string>,
    _reserveController: PromiseOrValue<string>,
    _devVesting: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  mintAuthority(overrides?: CallOverrides): Promise<string>;

  mintWell(
    wellIdHash: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  name(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  publicRecipient(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  reserveController(overrides?: CallOverrides): Promise<string>;

  setMintAuthority(
    _mintAuthority: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  symbol(overrides?: CallOverrides): Promise<string>;

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  transfer(
    to: PromiseOrValue<string>,
    value: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferFrom(
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    value: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    BPS_DENOM(overrides?: CallOverrides): Promise<number>;

    DEV_BPS(overrides?: CallOverrides): Promise<number>;

    MINT_UNIT(overrides?: CallOverrides): Promise<BigNumber>;

    PUBLIC_BPS(overrides?: CallOverrides): Promise<number>;

    RESERVE_BPS(overrides?: CallOverrides): Promise<number>;

    allowance(
      owner: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    balanceOf(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<number>;

    devVesting(overrides?: CallOverrides): Promise<string>;

    genesisCutoffTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    genesisInitialized(overrides?: CallOverrides): Promise<boolean>;

    genesisSnapshotHash(overrides?: CallOverrides): Promise<string>;

    initializeGenesis(
      genesisSupply: PromiseOrValue<BigNumberish>,
      cutoffTimestamp: PromiseOrValue<BigNumberish>,
      snapshotHash: PromiseOrValue<BytesLike>,
      _publicRecipient: PromiseOrValue<string>,
      _reserveController: PromiseOrValue<string>,
      _devVesting: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    mintAuthority(overrides?: CallOverrides): Promise<string>;

    mintWell(
      wellIdHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    name(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    publicRecipient(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    reserveController(overrides?: CallOverrides): Promise<string>;

    setMintAuthority(
      _mintAuthority: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    symbol(overrides?: CallOverrides): Promise<string>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Approval(address,address,uint256)"(
      owner?: PromiseOrValue<string> | null,
      spender?: PromiseOrValue<string> | null,
      value?: null
    ): ApprovalEventFilter;
    Approval(
      owner?: PromiseOrValue<string> | null,
      spender?: PromiseOrValue<string> | null,
      value?: null
    ): ApprovalEventFilter;

    "GenesisInitialized(uint256,uint64,bytes32,address,address,address)"(
      genesisSupply?: null,
      cutoffTimestamp?: null,
      snapshotHash?: null,
      publicRecipient?: null,
      reserveController?: null,
      devVesting?: null
    ): GenesisInitializedEventFilter;
    GenesisInitialized(
      genesisSupply?: null,
      cutoffTimestamp?: null,
      snapshotHash?: null,
      publicRecipient?: null,
      reserveController?: null,
      devVesting?: null
    ): GenesisInitializedEventFilter;

    "GenesisMetadata(uint64,bytes32)"(
      cutoffTimestamp?: null,
      snapshotHash?: null
    ): GenesisMetadataEventFilter;
    GenesisMetadata(
      cutoffTimestamp?: null,
      snapshotHash?: null
    ): GenesisMetadataEventFilter;

    "MintAuthoritySet(address)"(
      mintAuthority?: null
    ): MintAuthoritySetEventFilter;
    MintAuthoritySet(mintAuthority?: null): MintAuthoritySetEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Transfer(address,address,uint256)"(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      value?: null
    ): TransferEventFilter;
    Transfer(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      value?: null
    ): TransferEventFilter;

    "WellMinted(bytes32,address,uint256,uint256,uint256)"(
      wellIdHash?: PromiseOrValue<BytesLike> | null,
      to?: PromiseOrValue<string> | null,
      amount?: null,
      newTotalSupply?: null,
      timestamp?: null
    ): WellMintedEventFilter;
    WellMinted(
      wellIdHash?: PromiseOrValue<BytesLike> | null,
      to?: PromiseOrValue<string> | null,
      amount?: null,
      newTotalSupply?: null,
      timestamp?: null
    ): WellMintedEventFilter;
  };

  estimateGas: {
    BPS_DENOM(overrides?: CallOverrides): Promise<BigNumber>;

    DEV_BPS(overrides?: CallOverrides): Promise<BigNumber>;

    MINT_UNIT(overrides?: CallOverrides): Promise<BigNumber>;

    PUBLIC_BPS(overrides?: CallOverrides): Promise<BigNumber>;

    RESERVE_BPS(overrides?: CallOverrides): Promise<BigNumber>;

    allowance(
      owner: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    balanceOf(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<BigNumber>;

    devVesting(overrides?: CallOverrides): Promise<BigNumber>;

    genesisCutoffTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    genesisInitialized(overrides?: CallOverrides): Promise<BigNumber>;

    genesisSnapshotHash(overrides?: CallOverrides): Promise<BigNumber>;

    initializeGenesis(
      genesisSupply: PromiseOrValue<BigNumberish>,
      cutoffTimestamp: PromiseOrValue<BigNumberish>,
      snapshotHash: PromiseOrValue<BytesLike>,
      _publicRecipient: PromiseOrValue<string>,
      _reserveController: PromiseOrValue<string>,
      _devVesting: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    mintAuthority(overrides?: CallOverrides): Promise<BigNumber>;

    mintWell(
      wellIdHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    publicRecipient(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    reserveController(overrides?: CallOverrides): Promise<BigNumber>;

    setMintAuthority(
      _mintAuthority: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    BPS_DENOM(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DEV_BPS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MINT_UNIT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PUBLIC_BPS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    RESERVE_BPS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    allowance(
      owner: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    approve(
      spender: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    balanceOf(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    decimals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    devVesting(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    genesisCutoffTimestamp(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    genesisInitialized(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    genesisSnapshotHash(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initializeGenesis(
      genesisSupply: PromiseOrValue<BigNumberish>,
      cutoffTimestamp: PromiseOrValue<BigNumberish>,
      snapshotHash: PromiseOrValue<BytesLike>,
      _publicRecipient: PromiseOrValue<string>,
      _reserveController: PromiseOrValue<string>,
      _devVesting: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    mintAuthority(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mintWell(
      wellIdHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    publicRecipient(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    reserveController(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setMintAuthority(
      _mintAuthority: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transfer(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
