/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface DevVestingInterface extends utils.Interface {
  functions: {
    "MONTH()": FunctionFragment;
    "MONTHS()": FunctionFragment;
    "beneficiary()": FunctionFragment;
    "launchTime()": FunctionFragment;
    "monthlyAmount()": FunctionFragment;
    "releasable()": FunctionFragment;
    "release()": FunctionFragment;
    "released()": FunctionFragment;
    "requiredFunding()": FunctionFragment;
    "roundingRemainder()": FunctionFragment;
    "token()": FunctionFragment;
    "totalAllocation()": FunctionFragment;
    "vestedAmount(uint64)": FunctionFragment;
    "vestingEndTime()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "MONTH"
      | "MONTHS"
      | "beneficiary"
      | "launchTime"
      | "monthlyAmount"
      | "releasable"
      | "release"
      | "released"
      | "requiredFunding"
      | "roundingRemainder"
      | "token"
      | "totalAllocation"
      | "vestedAmount"
      | "vestingEndTime"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "MONTH", values?: undefined): string;
  encodeFunctionData(functionFragment: "MONTHS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "beneficiary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "launchTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "monthlyAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "releasable",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "release", values?: undefined): string;
  encodeFunctionData(functionFragment: "released", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requiredFunding",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "roundingRemainder",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalAllocation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vestedAmount",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "vestingEndTime",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "MONTH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MONTHS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "beneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "launchTime", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "monthlyAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "releasable", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "released", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requiredFunding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roundingRemainder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAllocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestingEndTime",
    data: BytesLike
  ): Result;

  events: {
    "TokensReleased(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "TokensReleased"): EventFragment;
}

export interface TokensReleasedEventObject {
  beneficiary: string;
  amount: BigNumber;
}
export type TokensReleasedEvent = TypedEvent<
  [string, BigNumber],
  TokensReleasedEventObject
>;

export type TokensReleasedEventFilter = TypedEventFilter<TokensReleasedEvent>;

export interface DevVesting extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DevVestingInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MONTH(overrides?: CallOverrides): Promise<[BigNumber]>;

    MONTHS(overrides?: CallOverrides): Promise<[number]>;

    beneficiary(overrides?: CallOverrides): Promise<[string]>;

    launchTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    monthlyAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    releasable(overrides?: CallOverrides): Promise<[BigNumber]>;

    release(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    released(overrides?: CallOverrides): Promise<[BigNumber]>;

    requiredFunding(overrides?: CallOverrides): Promise<[BigNumber]>;

    roundingRemainder(overrides?: CallOverrides): Promise<[BigNumber]>;

    token(overrides?: CallOverrides): Promise<[string]>;

    totalAllocation(overrides?: CallOverrides): Promise<[BigNumber]>;

    vestedAmount(
      timestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    vestingEndTime(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  MONTH(overrides?: CallOverrides): Promise<BigNumber>;

  MONTHS(overrides?: CallOverrides): Promise<number>;

  beneficiary(overrides?: CallOverrides): Promise<string>;

  launchTime(overrides?: CallOverrides): Promise<BigNumber>;

  monthlyAmount(overrides?: CallOverrides): Promise<BigNumber>;

  releasable(overrides?: CallOverrides): Promise<BigNumber>;

  release(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  released(overrides?: CallOverrides): Promise<BigNumber>;

  requiredFunding(overrides?: CallOverrides): Promise<BigNumber>;

  roundingRemainder(overrides?: CallOverrides): Promise<BigNumber>;

  token(overrides?: CallOverrides): Promise<string>;

  totalAllocation(overrides?: CallOverrides): Promise<BigNumber>;

  vestedAmount(
    timestamp: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  vestingEndTime(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    MONTH(overrides?: CallOverrides): Promise<BigNumber>;

    MONTHS(overrides?: CallOverrides): Promise<number>;

    beneficiary(overrides?: CallOverrides): Promise<string>;

    launchTime(overrides?: CallOverrides): Promise<BigNumber>;

    monthlyAmount(overrides?: CallOverrides): Promise<BigNumber>;

    releasable(overrides?: CallOverrides): Promise<BigNumber>;

    release(overrides?: CallOverrides): Promise<void>;

    released(overrides?: CallOverrides): Promise<BigNumber>;

    requiredFunding(overrides?: CallOverrides): Promise<BigNumber>;

    roundingRemainder(overrides?: CallOverrides): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<string>;

    totalAllocation(overrides?: CallOverrides): Promise<BigNumber>;

    vestedAmount(
      timestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    vestingEndTime(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "TokensReleased(address,uint256)"(
      beneficiary?: PromiseOrValue<string> | null,
      amount?: null
    ): TokensReleasedEventFilter;
    TokensReleased(
      beneficiary?: PromiseOrValue<string> | null,
      amount?: null
    ): TokensReleasedEventFilter;
  };

  estimateGas: {
    MONTH(overrides?: CallOverrides): Promise<BigNumber>;

    MONTHS(overrides?: CallOverrides): Promise<BigNumber>;

    beneficiary(overrides?: CallOverrides): Promise<BigNumber>;

    launchTime(overrides?: CallOverrides): Promise<BigNumber>;

    monthlyAmount(overrides?: CallOverrides): Promise<BigNumber>;

    releasable(overrides?: CallOverrides): Promise<BigNumber>;

    release(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    released(overrides?: CallOverrides): Promise<BigNumber>;

    requiredFunding(overrides?: CallOverrides): Promise<BigNumber>;

    roundingRemainder(overrides?: CallOverrides): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<BigNumber>;

    totalAllocation(overrides?: CallOverrides): Promise<BigNumber>;

    vestedAmount(
      timestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    vestingEndTime(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    MONTH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MONTHS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    beneficiary(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    launchTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    monthlyAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    releasable(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    release(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    released(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    requiredFunding(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    roundingRemainder(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    token(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalAllocation(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    vestedAmount(
      timestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    vestingEndTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
