/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as oracleMinterSol from "./OracleMinter.sol";
export type { oracleMinterSol };
import type * as reserveControllerSol from "./ReserveController.sol";
export type { reserveControllerSol };
export type { CAPITToken } from "./CAPITToken";
export type { DevVesting } from "./DevVesting";
