/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICAPITToken,
  ICAPITTokenInterface,
} from "../../../contracts/OracleMinter.sol/ICAPITToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "wellIdHash",
        type: "bytes32",
      },
    ],
    name: "mintWell",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICAPITToken__factory {
  static readonly abi = _abi;
  static createInterface(): ICAPITTokenInterface {
    return new utils.Interface(_abi) as ICAPITTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICAPITToken {
    return new Contract(address, _abi, signerOrProvider) as ICAPITToken;
  }
}
