/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ReserveControllerInterface extends utils.Interface {
  functions: {
    "addLiquidity(uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
    "capit()": FunctionFragment;
    "capitUsedInWindow()": FunctionFragment;
    "cooldownSeconds()": FunctionFragment;
    "lastAddLiquidityAt()": FunctionFragment;
    "lpLocker()": FunctionFragment;
    "lpPair()": FunctionFragment;
    "maxCapitPer30d()": FunctionFragment;
    "maxQuotePer30d()": FunctionFragment;
    "operator()": FunctionFragment;
    "quote()": FunctionFragment;
    "quoteUsedInWindow()": FunctionFragment;
    "recoverNonCoreToken(address,address,uint256)": FunctionFragment;
    "router()": FunctionFragment;
    "windowStart()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addLiquidity"
      | "capit"
      | "capitUsedInWindow"
      | "cooldownSeconds"
      | "lastAddLiquidityAt"
      | "lpLocker"
      | "lpPair"
      | "maxCapitPer30d"
      | "maxQuotePer30d"
      | "operator"
      | "quote"
      | "quoteUsedInWindow"
      | "recoverNonCoreToken"
      | "router"
      | "windowStart"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "capit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "capitUsedInWindow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cooldownSeconds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastAddLiquidityAt",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lpLocker", values?: undefined): string;
  encodeFunctionData(functionFragment: "lpPair", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maxCapitPer30d",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxQuotePer30d",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "operator", values?: undefined): string;
  encodeFunctionData(functionFragment: "quote", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "quoteUsedInWindow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recoverNonCoreToken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "router", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "windowStart",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "capit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "capitUsedInWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cooldownSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastAddLiquidityAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lpLocker", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lpPair", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxCapitPer30d",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxQuotePer30d",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "quote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quoteUsedInWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverNonCoreToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "router", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "windowStart",
    data: BytesLike
  ): Result;

  events: {
    "LiquidityAdded(uint256,uint256,uint256,address,address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LiquidityAdded"): EventFragment;
}

export interface LiquidityAddedEventObject {
  capitAmount: BigNumber;
  quoteAmount: BigNumber;
  liquidity: BigNumber;
  router: string;
  lpPair: string;
  lpLocker: string;
  timestamp: BigNumber;
}
export type LiquidityAddedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, string, string, string, BigNumber],
  LiquidityAddedEventObject
>;

export type LiquidityAddedEventFilter = TypedEventFilter<LiquidityAddedEvent>;

export interface ReserveController extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ReserveControllerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addLiquidity(
      capitAmount: PromiseOrValue<BigNumberish>,
      quoteAmount: PromiseOrValue<BigNumberish>,
      capitMin: PromiseOrValue<BigNumberish>,
      quoteMin: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    capit(overrides?: CallOverrides): Promise<[string]>;

    capitUsedInWindow(overrides?: CallOverrides): Promise<[BigNumber]>;

    cooldownSeconds(overrides?: CallOverrides): Promise<[BigNumber]>;

    lastAddLiquidityAt(overrides?: CallOverrides): Promise<[BigNumber]>;

    lpLocker(overrides?: CallOverrides): Promise<[string]>;

    lpPair(overrides?: CallOverrides): Promise<[string]>;

    maxCapitPer30d(overrides?: CallOverrides): Promise<[BigNumber]>;

    maxQuotePer30d(overrides?: CallOverrides): Promise<[BigNumber]>;

    operator(overrides?: CallOverrides): Promise<[string]>;

    quote(overrides?: CallOverrides): Promise<[string]>;

    quoteUsedInWindow(overrides?: CallOverrides): Promise<[BigNumber]>;

    recoverNonCoreToken(
      token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    router(overrides?: CallOverrides): Promise<[string]>;

    windowStart(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  addLiquidity(
    capitAmount: PromiseOrValue<BigNumberish>,
    quoteAmount: PromiseOrValue<BigNumberish>,
    capitMin: PromiseOrValue<BigNumberish>,
    quoteMin: PromiseOrValue<BigNumberish>,
    deadline: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  capit(overrides?: CallOverrides): Promise<string>;

  capitUsedInWindow(overrides?: CallOverrides): Promise<BigNumber>;

  cooldownSeconds(overrides?: CallOverrides): Promise<BigNumber>;

  lastAddLiquidityAt(overrides?: CallOverrides): Promise<BigNumber>;

  lpLocker(overrides?: CallOverrides): Promise<string>;

  lpPair(overrides?: CallOverrides): Promise<string>;

  maxCapitPer30d(overrides?: CallOverrides): Promise<BigNumber>;

  maxQuotePer30d(overrides?: CallOverrides): Promise<BigNumber>;

  operator(overrides?: CallOverrides): Promise<string>;

  quote(overrides?: CallOverrides): Promise<string>;

  quoteUsedInWindow(overrides?: CallOverrides): Promise<BigNumber>;

  recoverNonCoreToken(
    token: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  router(overrides?: CallOverrides): Promise<string>;

  windowStart(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    addLiquidity(
      capitAmount: PromiseOrValue<BigNumberish>,
      quoteAmount: PromiseOrValue<BigNumberish>,
      capitMin: PromiseOrValue<BigNumberish>,
      quoteMin: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        usedCapit: BigNumber;
        usedQuote: BigNumber;
        liquidity: BigNumber;
      }
    >;

    capit(overrides?: CallOverrides): Promise<string>;

    capitUsedInWindow(overrides?: CallOverrides): Promise<BigNumber>;

    cooldownSeconds(overrides?: CallOverrides): Promise<BigNumber>;

    lastAddLiquidityAt(overrides?: CallOverrides): Promise<BigNumber>;

    lpLocker(overrides?: CallOverrides): Promise<string>;

    lpPair(overrides?: CallOverrides): Promise<string>;

    maxCapitPer30d(overrides?: CallOverrides): Promise<BigNumber>;

    maxQuotePer30d(overrides?: CallOverrides): Promise<BigNumber>;

    operator(overrides?: CallOverrides): Promise<string>;

    quote(overrides?: CallOverrides): Promise<string>;

    quoteUsedInWindow(overrides?: CallOverrides): Promise<BigNumber>;

    recoverNonCoreToken(
      token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    router(overrides?: CallOverrides): Promise<string>;

    windowStart(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "LiquidityAdded(uint256,uint256,uint256,address,address,address,uint256)"(
      capitAmount?: null,
      quoteAmount?: null,
      liquidity?: null,
      router?: null,
      lpPair?: null,
      lpLocker?: null,
      timestamp?: null
    ): LiquidityAddedEventFilter;
    LiquidityAdded(
      capitAmount?: null,
      quoteAmount?: null,
      liquidity?: null,
      router?: null,
      lpPair?: null,
      lpLocker?: null,
      timestamp?: null
    ): LiquidityAddedEventFilter;
  };

  estimateGas: {
    addLiquidity(
      capitAmount: PromiseOrValue<BigNumberish>,
      quoteAmount: PromiseOrValue<BigNumberish>,
      capitMin: PromiseOrValue<BigNumberish>,
      quoteMin: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    capit(overrides?: CallOverrides): Promise<BigNumber>;

    capitUsedInWindow(overrides?: CallOverrides): Promise<BigNumber>;

    cooldownSeconds(overrides?: CallOverrides): Promise<BigNumber>;

    lastAddLiquidityAt(overrides?: CallOverrides): Promise<BigNumber>;

    lpLocker(overrides?: CallOverrides): Promise<BigNumber>;

    lpPair(overrides?: CallOverrides): Promise<BigNumber>;

    maxCapitPer30d(overrides?: CallOverrides): Promise<BigNumber>;

    maxQuotePer30d(overrides?: CallOverrides): Promise<BigNumber>;

    operator(overrides?: CallOverrides): Promise<BigNumber>;

    quote(overrides?: CallOverrides): Promise<BigNumber>;

    quoteUsedInWindow(overrides?: CallOverrides): Promise<BigNumber>;

    recoverNonCoreToken(
      token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    router(overrides?: CallOverrides): Promise<BigNumber>;

    windowStart(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addLiquidity(
      capitAmount: PromiseOrValue<BigNumberish>,
      quoteAmount: PromiseOrValue<BigNumberish>,
      capitMin: PromiseOrValue<BigNumberish>,
      quoteMin: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    capit(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    capitUsedInWindow(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cooldownSeconds(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastAddLiquidityAt(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lpLocker(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lpPair(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxCapitPer30d(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxQuotePer30d(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    operator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    quote(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    quoteUsedInWindow(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    recoverNonCoreToken(
      token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    router(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    windowStart(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
