/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface OracleMinterInterface extends utils.Interface {
  functions: {
    "capit()": FunctionFragment;
    "isAuthorizedCaller(address)": FunctionFragment;
    "mintWell(bytes32,bytes32)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setAuthorizedCaller(address,bool)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "wellMinted(bytes32)": FunctionFragment;
    "wellProofHash(bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "capit"
      | "isAuthorizedCaller"
      | "mintWell"
      | "owner"
      | "renounceOwnership"
      | "setAuthorizedCaller"
      | "transferOwnership"
      | "wellMinted"
      | "wellProofHash"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "capit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedCaller",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "mintWell",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedCaller",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "wellMinted",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "wellProofHash",
    values: [PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(functionFragment: "capit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintWell", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wellMinted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "wellProofHash",
    data: BytesLike
  ): Result;

  events: {
    "AuthorizedCallerSet(address,bool)": EventFragment;
    "OracleMintTriggered(address,bytes32,bytes32,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "WellIdConsumed(bytes32,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AuthorizedCallerSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OracleMintTriggered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WellIdConsumed"): EventFragment;
}

export interface AuthorizedCallerSetEventObject {
  caller: string;
  allowed: boolean;
}
export type AuthorizedCallerSetEvent = TypedEvent<
  [string, boolean],
  AuthorizedCallerSetEventObject
>;

export type AuthorizedCallerSetEventFilter =
  TypedEventFilter<AuthorizedCallerSetEvent>;

export interface OracleMintTriggeredEventObject {
  caller: string;
  wellIdHash: string;
  proofHash: string;
  timestamp: BigNumber;
}
export type OracleMintTriggeredEvent = TypedEvent<
  [string, string, string, BigNumber],
  OracleMintTriggeredEventObject
>;

export type OracleMintTriggeredEventFilter =
  TypedEventFilter<OracleMintTriggeredEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface WellIdConsumedEventObject {
  wellIdHash: string;
  proofHash: string;
}
export type WellIdConsumedEvent = TypedEvent<
  [string, string],
  WellIdConsumedEventObject
>;

export type WellIdConsumedEventFilter = TypedEventFilter<WellIdConsumedEvent>;

export interface OracleMinter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OracleMinterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    capit(overrides?: CallOverrides): Promise<[string]>;

    isAuthorizedCaller(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    mintWell(
      wellIdHash: PromiseOrValue<BytesLike>,
      proofHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setAuthorizedCaller(
      caller: PromiseOrValue<string>,
      allowed: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    wellMinted(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    wellProofHash(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  capit(overrides?: CallOverrides): Promise<string>;

  isAuthorizedCaller(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  mintWell(
    wellIdHash: PromiseOrValue<BytesLike>,
    proofHash: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setAuthorizedCaller(
    caller: PromiseOrValue<string>,
    allowed: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  wellMinted(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  wellProofHash(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    capit(overrides?: CallOverrides): Promise<string>;

    isAuthorizedCaller(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    mintWell(
      wellIdHash: PromiseOrValue<BytesLike>,
      proofHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setAuthorizedCaller(
      caller: PromiseOrValue<string>,
      allowed: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    wellMinted(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    wellProofHash(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "AuthorizedCallerSet(address,bool)"(
      caller?: PromiseOrValue<string> | null,
      allowed?: null
    ): AuthorizedCallerSetEventFilter;
    AuthorizedCallerSet(
      caller?: PromiseOrValue<string> | null,
      allowed?: null
    ): AuthorizedCallerSetEventFilter;

    "OracleMintTriggered(address,bytes32,bytes32,uint256)"(
      caller?: PromiseOrValue<string> | null,
      wellIdHash?: PromiseOrValue<BytesLike> | null,
      proofHash?: PromiseOrValue<BytesLike> | null,
      timestamp?: null
    ): OracleMintTriggeredEventFilter;
    OracleMintTriggered(
      caller?: PromiseOrValue<string> | null,
      wellIdHash?: PromiseOrValue<BytesLike> | null,
      proofHash?: PromiseOrValue<BytesLike> | null,
      timestamp?: null
    ): OracleMintTriggeredEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "WellIdConsumed(bytes32,bytes32)"(
      wellIdHash?: PromiseOrValue<BytesLike> | null,
      proofHash?: PromiseOrValue<BytesLike> | null
    ): WellIdConsumedEventFilter;
    WellIdConsumed(
      wellIdHash?: PromiseOrValue<BytesLike> | null,
      proofHash?: PromiseOrValue<BytesLike> | null
    ): WellIdConsumedEventFilter;
  };

  estimateGas: {
    capit(overrides?: CallOverrides): Promise<BigNumber>;

    isAuthorizedCaller(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mintWell(
      wellIdHash: PromiseOrValue<BytesLike>,
      proofHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setAuthorizedCaller(
      caller: PromiseOrValue<string>,
      allowed: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    wellMinted(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    wellProofHash(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    capit(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isAuthorizedCaller(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mintWell(
      wellIdHash: PromiseOrValue<BytesLike>,
      proofHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setAuthorizedCaller(
      caller: PromiseOrValue<string>,
      allowed: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    wellMinted(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    wellProofHash(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
