/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IUniswapV2FactoryLike,
  IUniswapV2FactoryLikeInterface,
} from "../../../contracts/ReserveController.sol/IUniswapV2FactoryLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenA",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenB",
        type: "address",
      },
    ],
    name: "getPair",
    outputs: [
      {
        internalType: "address",
        name: "pair",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IUniswapV2FactoryLike__factory {
  static readonly abi = _abi;
  static createInterface(): IUniswapV2FactoryLikeInterface {
    return new utils.Interface(_abi) as IUniswapV2FactoryLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUniswapV2FactoryLike {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IUniswapV2FactoryLike;
  }
}
