/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Errors__factory>;
    getContractFactory(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Errors__factory>;
    getContractFactory(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Errors__factory>;
    getContractFactory(
      name: "IERC1363",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1363__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "SafeERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeERC20__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "CAPITToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CAPITToken__factory>;
    getContractFactory(
      name: "DevVesting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DevVesting__factory>;
    getContractFactory(
      name: "ICAPITToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICAPITToken__factory>;
    getContractFactory(
      name: "OracleMinter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OracleMinter__factory>;
    getContractFactory(
      name: "IUniswapV2FactoryLike",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV2FactoryLike__factory>;
    getContractFactory(
      name: "IUniswapV2RouterLike",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV2RouterLike__factory>;
    getContractFactory(
      name: "ReserveController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReserveController__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC1155Errors",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Errors>;
    getContractAt(
      name: "IERC20Errors",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Errors>;
    getContractAt(
      name: "IERC721Errors",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Errors>;
    getContractAt(
      name: "IERC1363",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1363>;
    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "SafeERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeERC20>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "CAPITToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CAPITToken>;
    getContractAt(
      name: "DevVesting",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DevVesting>;
    getContractAt(
      name: "ICAPITToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ICAPITToken>;
    getContractAt(
      name: "OracleMinter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OracleMinter>;
    getContractAt(
      name: "IUniswapV2FactoryLike",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV2FactoryLike>;
    getContractAt(
      name: "IUniswapV2RouterLike",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV2RouterLike>;
    getContractAt(
      name: "ReserveController",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ReserveController>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
